In [3]:
import numpy as np
import pandas as pd
import sklearn
import numpy as np
!pip install yapf


In [151]:
from sklearn import datasets
from sklearn.cross_validation import train_test_split
iris = sklearn.datasets.load_iris()



x = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.50, random_state=42)

number_features = x.shape[1]
number_classes = np.max(iris.target) + 1
num_obs = x.shape[0]
b = np.ones(number_classes)

print('Shape of x is: {}'.format(x.shape))
print('Shape of y is: {}'.format(y.shape))

print('No Obs {}'.format(num_obs))
print('No classes {}'.format(number_classes))
print('No Feats {}'.format(number_features))

#Weights vector is Rows = Features * Cols = Classes
w_shape = (number_features, number_classes)
w = np.zeros(w_shape)

w

Shape of x is: (150, 4)
Shape of y is: (150,)
No Obs 150
No classes 3
No Feats 4


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [152]:
def _one_hot(y, n_labels, dtype):

    mat = np.zeros((len(y), n_labels))
    for i, val in enumerate(y):
        mat[i, val] = 1
    return mat.astype(dtype)


y_enc = _one_hot(y, 3, np.float)
print('Shape of y is: {}'.format(y_enc.shape))
y_enc

Shape of y is: (150, 3)


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [153]:
#weights vector needs to have a row for each feature, and a column for each class
#We have 2 observations, and 3 classes
def softmax(z):
    return (np.exp(z.T) / np.sum(np.exp(z), axis=1)).T


def cross_entropy(output, y_target):
    return -np.sum(np.log(output) * (y_target), axis=1)


net_input = x.dot(w) + b
y_probs = softmax(net_input)
cost = []
for i in range(1, 10001):
    diff = y_probs - y_enc
    grad = np.dot(x.T, diff)/y.size
    learning_rate = .1
    w -= learning_rate * grad
    loss = cross_entropy(y_probs, y_enc)
    cost.append(loss)
    net_input = x.dot(w) + b
    y_probs = softmax(net_input)

for i, j in enumerate(cost):
    print('epoch {}, cost {}'.format((i + 1), (np.round(np.mean(j), 10))))

epoch 1, cost 1.0986122887
epoch 2, cost 1.0326190595
epoch 3, cost 0.975624876
epoch 4, cost 0.9309311684
epoch 5, cost 0.8993678147
epoch 6, cost 0.8769056051
epoch 7, cost 0.8659100063
epoch 8, cost 0.8665535699
epoch 9, cost 0.8596059641
epoch 10, cost 0.8708813204
epoch 11, cost 0.843529215
epoch 12, cost 0.85620341
epoch 13, cost 0.8140106113
epoch 14, cost 0.8319276972
epoch 15, cost 0.7850998331
epoch 16, cost 0.8093806707
epoch 17, cost 0.7603792808
epoch 18, cost 0.7898519095
epoch 19, cost 0.739331932
epoch 20, cost 0.7728321183
epoch 21, cost 0.7211223135
epoch 22, cost 0.7577591595
epoch 23, cost 0.7051099151
epoch 24, cost 0.7442065338
epoch 25, cost 0.6908287423
epoch 26, cost 0.7318593707
epoch 27, cost 0.6779347931
epoch 28, cost 0.7204817947
epoch 29, cost 0.6661689676
epoch 30, cost 0.7098940005
epoch 31, cost 0.6553324994
epoch 32, cost 0.6999567222
epoch 33, cost 0.6452703976
epoch 34, cost 0.6905605347
epoch 35, cost 0.6358600351
epoch 36, cost 0.6816183462
epoch 

epoch 2477, cost 0.0988590683
epoch 2478, cost 0.0988481952
epoch 2479, cost 0.09883733
epoch 2480, cost 0.0988264728
epoch 2481, cost 0.0988156235
epoch 2482, cost 0.0988047822
epoch 2483, cost 0.0987939488
epoch 2484, cost 0.0987831233
epoch 2485, cost 0.0987723057
epoch 2486, cost 0.0987614961
epoch 2487, cost 0.0987506943
epoch 2488, cost 0.0987399004
epoch 2489, cost 0.0987291144
epoch 2490, cost 0.0987183362
epoch 2491, cost 0.098707566
epoch 2492, cost 0.0986968035
epoch 2493, cost 0.0986860489
epoch 2494, cost 0.0986753022
epoch 2495, cost 0.0986645633
epoch 2496, cost 0.0986538321
epoch 2497, cost 0.0986431088
epoch 2498, cost 0.0986323933
epoch 2499, cost 0.0986216856
epoch 2500, cost 0.0986109857
epoch 2501, cost 0.0986002935
epoch 2502, cost 0.0985896091
epoch 2503, cost 0.0985789325
epoch 2504, cost 0.0985682636
epoch 2505, cost 0.0985576025
epoch 2506, cost 0.098546949
epoch 2507, cost 0.0985363033
epoch 2508, cost 0.0985256654
epoch 2509, cost 0.0985150351
epoch 2510, co

epoch 4697, cost 0.0855626808
epoch 4698, cost 0.0855593981
epoch 4699, cost 0.0855561169
epoch 4700, cost 0.0855528369
epoch 4701, cost 0.0855495583
epoch 4702, cost 0.0855462811
epoch 4703, cost 0.0855430052
epoch 4704, cost 0.0855397307
epoch 4705, cost 0.0855364575
epoch 4706, cost 0.0855331857
epoch 4707, cost 0.0855299152
epoch 4708, cost 0.085526646
epoch 4709, cost 0.0855233782
epoch 4710, cost 0.0855201118
epoch 4711, cost 0.0855168467
epoch 4712, cost 0.0855135829
epoch 4713, cost 0.0855103204
epoch 4714, cost 0.0855070593
epoch 4715, cost 0.0855037996
epoch 4716, cost 0.0855005412
epoch 4717, cost 0.0854972841
epoch 4718, cost 0.0854940283
epoch 4719, cost 0.0854907739
epoch 4720, cost 0.0854875208
epoch 4721, cost 0.0854842691
epoch 4722, cost 0.0854810187
epoch 4723, cost 0.0854777696
epoch 4724, cost 0.0854745219
epoch 4725, cost 0.0854712754
epoch 4726, cost 0.0854680304
epoch 4727, cost 0.0854647866
epoch 4728, cost 0.0854615442
epoch 4729, cost 0.0854583031
epoch 4730,

epoch 7197, cost 0.0801706361
epoch 7198, cost 0.0801692295
epoch 7199, cost 0.0801678234
epoch 7200, cost 0.0801664176
epoch 7201, cost 0.0801650122
epoch 7202, cost 0.0801636073
epoch 7203, cost 0.0801622027
epoch 7204, cost 0.0801607985
epoch 7205, cost 0.0801593948
epoch 7206, cost 0.0801579914
epoch 7207, cost 0.0801565884
epoch 7208, cost 0.0801551859
epoch 7209, cost 0.0801537837
epoch 7210, cost 0.0801523819
epoch 7211, cost 0.0801509805
epoch 7212, cost 0.0801495795
epoch 7213, cost 0.0801481789
epoch 7214, cost 0.0801467787
epoch 7215, cost 0.0801453789
epoch 7216, cost 0.0801439795
epoch 7217, cost 0.0801425805
epoch 7218, cost 0.0801411819
epoch 7219, cost 0.0801397837
epoch 7220, cost 0.0801383859
epoch 7221, cost 0.0801369885
epoch 7222, cost 0.0801355914
epoch 7223, cost 0.0801341948
epoch 7224, cost 0.0801327986
epoch 7225, cost 0.0801314027
epoch 7226, cost 0.0801300073
epoch 7227, cost 0.0801286122
epoch 7228, cost 0.0801272176
epoch 7229, cost 0.0801258233
epoch 7230

epoch 9696, cost 0.0775868966
epoch 9697, cost 0.0775861412
epoch 9698, cost 0.077585386
epoch 9699, cost 0.077584631
epoch 9700, cost 0.0775838761
epoch 9701, cost 0.0775831214
epoch 9702, cost 0.0775823669
epoch 9703, cost 0.0775816125
epoch 9704, cost 0.0775808583
epoch 9705, cost 0.0775801042
epoch 9706, cost 0.0775793504
epoch 9707, cost 0.0775785967
epoch 9708, cost 0.0775778431
epoch 9709, cost 0.0775770897
epoch 9710, cost 0.0775763365
epoch 9711, cost 0.0775755835
epoch 9712, cost 0.0775748306
epoch 9713, cost 0.0775740779
epoch 9714, cost 0.0775733254
epoch 9715, cost 0.077572573
epoch 9716, cost 0.0775718208
epoch 9717, cost 0.0775710687
epoch 9718, cost 0.0775703168
epoch 9719, cost 0.0775695651
epoch 9720, cost 0.0775688135
epoch 9721, cost 0.0775680621
epoch 9722, cost 0.0775673109
epoch 9723, cost 0.0775665599
epoch 9724, cost 0.077565809
epoch 9725, cost 0.0775650582
epoch 9726, cost 0.0775643077
epoch 9727, cost 0.0775635572
epoch 9728, cost 0.077562807
epoch 9729, cos

### Build a simple Class

In [160]:
w
from sklearn.metrics import accuracy_score, confusion_matrix

test = X_test.dot(w) + b
probs = np.exp(test) / np.sum(np.exp(test))
preds = []
for i in probs:
    preds.append(np.argmax(i)) 

preds = np.asarray(preds)

accuracy_score(y_test, preds)
c = confusion_matrix(y_test, preds, labels = [0,1])
c

array([[29,  0],
       [ 0, 23]], dtype=int64)